-- ============================================================
-- STEP 5.4 — Roles and permissions (RBAC)
-- ============================================================

-- Create roles
CREATE ROLE IF NOT EXISTS LOADER_ROLE;
COMMENT ON ROLE LOADER_ROLE IS 'Used by Snowpipe only — write access to RAW schema';

CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE;
COMMENT ON ROLE TRANSFORMER_ROLE IS 'Used by dbt only — read RAW, write STAGING/INTERMEDIATE/MARTS';

CREATE ROLE IF NOT EXISTS REPORTER_ROLE;
COMMENT ON ROLE REPORTER_ROLE IS 'Read-only access to MARTS schema — for BI tools';

-- LOADER_ROLE — Snowpipe writes raw data
GRANT USAGE ON DATABASE COMMERCE_DB TO ROLE LOADER_ROLE;
GRANT USAGE ON SCHEMA COMMERCE_DB.RAW TO ROLE LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA COMMERCE_DB.RAW TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA COMMERCE_DB.RAW TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE LOADER_ROLE;

-- TRANSFORMER_ROLE — dbt reads raw and writes everything else
GRANT USAGE ON DATABASE COMMERCE_DB TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA COMMERCE_DB.RAW TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA COMMERCE_DB.RAW TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA COMMERCE_DB.STAGING TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA COMMERCE_DB.INTERMEDIATE TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA COMMERCE_DB.MARTS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA COMMERCE_DB.MONITORING TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER_ROLE;

-- REPORTER_ROLE — BI tools read marts only
GRANT USAGE ON DATABASE COMMERCE_DB TO ROLE REPORTER_ROLE;
GRANT USAGE ON SCHEMA COMMERCE_DB.MARTS TO ROLE REPORTER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA COMMERCE_DB.MARTS TO ROLE REPORTER_ROLE;

-- Grant roles to your admin user so you can use them
GRANT ROLE LOADER_ROLE TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER_ROLE TO ROLE SYSADMIN;
GRANT ROLE REPORTER_ROLE TO ROLE SYSADMIN;