CREATE STORAGE INTEGRATION IF NOT EXISTS S3_COMMERCE_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::677276115158:role/snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://commerce-elt-raw-gbade/raw/');

DESC INTEGRATION S3_COMMERCE_INT;


ALTER STORAGE INTEGRATION S3_COMMERCE_INT
    SET STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::677276115158:role/snowflake-s3-role';

DESC INTEGRATION S3_COMMERCE_INT;