USE DATABASE COMMERCE_DB;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS COMMERCE_DB.RAW.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL', 'null', 'None')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = AUTO
    TIMESTAMP_FORMAT = AUTO
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE IF NOT EXISTS COMMERCE_DB.RAW.S3_CUSTOMERS_STAGE
    STORAGE_INTEGRATION = S3_COMMERCE_INT
    URL = 's3://commerce-elt-raw-gbade/raw/customers/'
    FILE_FORMAT = COMMERCE_DB.RAW.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS COMMERCE_DB.RAW.S3_PRODUCTS_STAGE
    STORAGE_INTEGRATION = S3_COMMERCE_INT
    URL = 's3://commerce-elt-raw-gbade/raw/products/'
    FILE_FORMAT = COMMERCE_DB.RAW.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS COMMERCE_DB.RAW.S3_ORDERS_STAGE
    STORAGE_INTEGRATION = S3_COMMERCE_INT
    URL = 's3://commerce-elt-raw-gbade/raw/orders/'
    FILE_FORMAT = COMMERCE_DB.RAW.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS COMMERCE_DB.RAW.S3_ORDER_ITEMS_STAGE
    STORAGE_INTEGRATION = S3_COMMERCE_INT
    URL = 's3://commerce-elt-raw-gbade/raw/order_items/'
    FILE_FORMAT = COMMERCE_DB.RAW.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS COMMERCE_DB.RAW.S3_EVENTS_STAGE
    STORAGE_INTEGRATION = S3_COMMERCE_INT
    URL = 's3://commerce-elt-raw-gbade/raw/events/'
    FILE_FORMAT = COMMERCE_DB.RAW.CSV_FORMAT;



LIST @COMMERCE_DB.RAW.S3_ORDERS_STAGE;